### ISSUE TITLE
Set tab-size from config

### ISSUE THREAD

**Issue by ivanmilov** [huih99/hjson-formatter#1]
Hello, 
by default the [stringify](https://github.com/huih99/hjson-formatter/blob/6bf560c45efcc563e49f9d660fe30ddc4aceca78/src/extension.ts#L25) function returns json text with tab-size==2.
I use tab-size==4 in all my projects. Is it possible to make this parameter configurable? Just need to pass another argument (e.g. 'space:4' ) into stringify here:
 https://github.com/huih99/hjson-formatter/blob/6bf560c45efcc563e49f9d660fe30ddc4aceca78/src/extension.ts#L25-L30

**Comment by huih99** [comment]
yes,that's my next step

**Comment by huih99** [comment]
version@0.2.0 already published, include customizations, see Readme

**Comment by ivanmilov** [comment]
Super, thank you 😀
