### ISSUE TITLE
Multiline strings gets formatted incorrectly

### ISSUE THREAD

**Issue by cwqt** [huih99/hjson-formatter#2]
This;

![image](https://user-images.githubusercontent.com/61694629/116947785-8821ce00-ac75-11eb-9486-5789f6a01f38.png)

Gets turned into:

![image](https://user-images.githubusercontent.com/61694629/116947794-8ce68200-ac75-11eb-96d6-5e968fddbe91.png)

`settings.json`
```
  "hjson-formatter.options": {
    "multiline": "std",
    "bracesSameLine": true,
    "space": 2
  },
```

**Comment by huih99** [comment]
In your case, the problem does arise, and if you want to keep the multiline string as it is, you need to set another option：
```json
"json-fomatter.options": {
    "separator": false
}
```
Note that even if you keep it as it is formatted, it will be parsed to a '\n' concatenated string when you finally convert it to JSON data using HJSON
