### ISSUE TITLE
formatter changes numbers

### ISSUE THREAD

**Issue by rlnt** [huih99/hjson-formatter#3]
When formatting with this extension, numbers are changed. I guess this is because of some datatype issue but this is a major issue.
Example:
```
{
    guild: 917126358974716233
    token: ljkalsdfkjhasdklhalsubhluashdkhafkdshuakdshug
    application_id: 962100125134577172
}
```
becomes this:
```
{
    guild: 917126358974716300
    token: ljkalsdfkjhasdklhalsubhluashdkhafkdshuakdshug
    application_id: 962100125134577200
}
```

**Comment by huih99** [comment]
In this example, using `JSON.stringify` to format it, I still get this wrong result, I don't know why, maybe the number exceeds the maximum number of JS 2^53 - 1

**Comment by rlnt** [comment]
Yeah, this is a precision issue. `Number.MAX_SAFE_INTEGER` is `2^53-1` as you said and therefore number higher than this lose precision.
The only solution for that would be using a big int library to parse it.
Something like this https://github.com/sidorares/json-bigint
